# action.yml
name: 'Run SDKMAN!'
description: 'Download the sdk you want to install'
inputs:
  candidate:
    description: 'The name of the candidate to install'
    required: true
  version:
    description: 'The version of the candidate to install'
    required: true
outputs:
  file:
    description: 'Filename of the downloaded archive.'
    value: ${{ steps.sdkman.outputs.file }}
runs:
  using: 'composite'
  steps:
    - id: sdkman
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.candidate }} ${{ inputs.version }} $(uname)
      shell: bash
